### PR TITLE
Added ability to impersonate user account when using a service account

### PR DESCRIPTION
**Pull request by craftycorvid**
Small change to allow Service Accounts to authenticate as other accounts in their domain.

### CODE REVIEW

**Comment by nya3jp** [comment]
Hi Ivan,

Thanks for your patch. It looks good to me.

In order to accept your patch, I need you to sign CLA (Contributor License Agreement), as described here:
https://github.com/google/hyou/blob/master/CONTRIBUTING.md

Could you check the page, sign CLA and then reply to this thread again?

Thanks!

**Comment by craftycorvid** [comment]
CLA has been signed on behalf of Leancode LLC.

**Comment by nya3jp** [comment]
@googlebot ping

**Comment by nya3jp** [comment]
Did you sign Corporate CLA? Then it takes a few days until Google verifies the submission.

I'll get back to you once CLA status is verified. Thanks!

**Comment by craftycorvid** [comment]
Just got an email saying:

> Google Contributor License Agreement for Leancode LLC has been voided for the following reason:

And that's it, no reason given.

**Comment by nya3jp** [comment]
Sorry for no reply for long time. But unfortunately I can't accept your patch without signed CLA. Please let me close this PR for now.

**Pull request closed without merging**
